name: 'Scheduled post in Brazilian'
on:
  schedule:
    - cron: '50 16 * * */3'
jobs:
  post-shrek:
    runs-on: ubuntu-latest
    steps:
      - uses: usafder/setup-node-with-cache@v1.0.0
      - name: 'Creating .env'
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
      - name: 'Post BR'
        run: npm run start
